modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="mianbaos_modernwarfare_vs2_compat"
version="${file.jarVersion}"
displayName="mianbao's ModernWarfare VS2 Compat"
authors="ling8"
description='''
Adds VS2 radar targeting and coordinate-guidance compatibility for mianbao's ModernWarfare.
'''

[[mixins]]
config="mianbaos_modernwarfare_vs2_compat.mixins.json"

[[dependencies.mianbaos_modernwarfare_vs2_compat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mianbaos_modernwarfare_vs2_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mianbaos_modernwarfare_vs2_compat]]
modId="valkyrienskies"
mandatory=true
versionRange="[2.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.mianbaos_modernwarfare_vs2_compat]]
modId="mianbaos_modernwarfare"
mandatory=true
versionRange="[2.2.0,)"
ordering="AFTER"
side="BOTH"
